"""change balance to usd cents, integer

Revision ID: 406dc8ed007a
Revises: 5732016144ca
Create Date: 2023-03-28 18:34:10.730726

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '406dc8ed007a'
down_revision = '5732016144ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('balance_usd_cents', sa.Integer(), nullable=False))
        batch_op.drop_column('balance')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('balance', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
        batch_op.drop_column('balance_usd_cents')

    # ### end Alembic commands ###
