"""add user balance

Revision ID: 934b6436288a
Revises: 80f3f719ce80
Create Date: 2023-03-28 17:12:54.853088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '934b6436288a'
down_revision = '80f3f719ce80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('balance', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('balance')

    # ### end Alembic commands ###
