"""restructure + remove example

Revision ID: fa62d3131d0b
Revises: 371825efc283
Create Date: 2023-03-28 14:35:34.721234

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa62d3131d0b'
down_revision = '371825efc283'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('example')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('example',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name='example_pkey')
    )
    # ### end Alembic commands ###
